### ISSUE TITLE
vault and placeholderapi error

### ISSUE THREAD

**Issue by JokerLiuPro** [GeorgH93/MarriageMaster#23] opened 2018-05-25 19:19 UTC
Plugin List
MarriageMaster version 2.0-RC2-SNAPSHOT-T20180523174610
PluginLib-1.0.2
Vault v1.6.6
PlaceholderAPI-2.8.7
 ChatControl 7.8.15

When enable Economy function 
https://hastebin.com/raw/uhutuvihom
When enable Chatcontrol included {marriagemaster_partner} (work without marriagemaster placeholder)
https://hastebin.com/raw/zowoyeceru

**Comment by GeorgH93** [comment] 2018-05-25 20:27
Thanks for the report.
The problem with economy is fixed in this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/24/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

The other problem is caused by clip's MarriageMaster placeholder extension. This extension only woks with Marriage Master V1.x builds. Marriage Master V2.x has it's own build in placeholder provider. If you remove the extension placeholders should work. For a list of all available placeholders please see: https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders

**Comment by JokerLiuPro** [comment] 2018-05-26 01:12
problem solved. thank you

**Comment by GeorgH93** [comment] 2018-05-26 17:01
Thanks for the report.
Bugfix is available: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/24/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

**Comment by JokerLiuPro** [comment] 2018-05-26 17:55
1. error when /marry someone (but work fine)
https://hastebin.com/pakatajaku.vbs
2. /marry update is not working without AutoUpdate: true
3. unknown spike. I will enable PluginLib MySQL next restart, hope it can reduce the spike.
(But so far it better than v1.x) 
https://i.imgur.com/6ZTFiCo.png

**Comment by GeorgH93** [comment] 2018-05-26 18:46
1. and 2. are fixed: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/26/artifact/target/MarriageMaster-2.0-RC2-SNAPSHOT.jar

3. 150ms for the marry command is definitely to long, it might has been caused by the error you have reported, but even for than it seems way to long. Can you please provide me with the full timings report.
Also, which economy plugin are you using?

**Comment by JokerLiuPro** [comment] 2018-05-27 04:56
craftconomy, but i haven't save the timings url ...
Also. can you add a option "no-op-permissions" OP's default don't have permissions access to everything. please? 
It cause personal data privacy issues to listen marry chat

**Comment by JokerLiuPro** [comment] 2018-05-27 16:42
marry set home issues
sometime when player /marry home it will Falling into The void
Database also show that home_y is under 0
https://i.imgur.com/Jly3qMi.png

**Comment by GeorgH93** [comment] 2018-05-27 21:49
I can see the problems with the chat surveillance function, especially with the GDPR. I have added an option to enable this feature (will be off by default from now on).
If your permission plugin honers the default permissions set in the plugin.yml op's shouldn't have access to all permissions (but most of them). If you would like to take away permissions from OP's please use your permission plugin for that. I now have also updated the permission matrix for V2.x: https://github.com/GeorgH93/MarriageMaster/wiki/Permissions

**Closed** 2018-06-04 11:20 UTC
Labels: V2, bug
