### ISSUE TITLE
Color code problem

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#125] opened 2020-03-29 20:26 UTC
Hello, at times the plugin seems to force line breaks because the characters are too long in the chat, the problem is that it no longer displays the color code.

Here is an example on my screen and my translation:

http://prntscr.com/rp0mms
Confirm: "&7[&4&lImperia&7] &2{DisplayName}&a veut t'épouser. Accepter la demande en mariage avec &2/marry accept &aou refusé avec &2/marry deny&a."

**Comment by GeorgH93** [comment] 2020-03-29 23:18
This is caused by how Minecraft is handling none JSON messages. I might improve converting non JSON messages to JSON in the future, but for now I have more important things to implement.

For now the workaround is to use JSON messages. I know they are annoying to work with, that's why we have developed the [Plugin Translation Page](https://ptp.pcgamingfreaks.at/). It provides a preview of the formatted message as well as an easy to use editor for JSON messages.
You can open your existing language file by using the `Userdefined` option in the `Choose the language file you want to edit` section.

**Comment by GeorgH93** [comment] 2020-03-29 23:50
Never mind, I just found a easy to implement solution as a temporary fix. I just use the MC 1.7 fallback code if the message is not JSON formatted. However, I would still recommend using JSON.
Should be fixed (for Bukkit only) with [this build](https://ci.pcgamingfreaks.at/job/MarriageMaster/165/artifact/artifacts/MarriageMaster-2.1.4-Release.jar).

For reference: https://github.com/GeorgH93/PCGF_PluginLib/issues/12

**Closed** 2020-04-07 23:05 UTC
Labels: bug
